# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_template <- function(object) {
    invisible(.Call(`_salad_set_template`, object))
}

fastNewDual <- function(x, d) {
    .Call(`_salad_fastNewDual`, x, d)
}

